version: "3"
services:
  api:
    build: ./backend
    ports:
      - "4000:4000"
    container_name: bordio-exam-backend
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: bordio-exam-client
